import { MineSnapshotTileId, type MineSnapshotRows } from '../types';

export function createDefaultMineSnapshot(): MineSnapshotRows {
  return [
    [
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Rock, reversed: !!Math.round(Math.random()) },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
    ],
    [
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Rock, reversed: !!Math.round(Math.random()) },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
    ],
    [
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Rock, reversed: !!Math.round(Math.random()) },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
    ],
    [
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Rock, reversed: !!Math.round(Math.random()) },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
    ],
    [
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Rock, reversed: !!Math.round(Math.random()) },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
    ],
    [
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Rock, reversed: !!Math.round(Math.random()) },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
    ],
    [
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Player },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
    ],
    [
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
    ],
    [
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
      { tileId: MineSnapshotTileId.Wall },
    ],
  ];
}
